# Generated by Django 4.1 on 2023-03-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Tool", "0002_dietmodel_delete_dietform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietmodel",
            name="Fecal_sample",
        ),
        migrations.RemoveField(
            model_name="dietmodel",
            name="Gender",
        ),
    ]
