# Generated by Django 4.1 on 2023-03-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tool", "0003_remove_dietmodel_fecal_sample_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietmodel",
            name="Fecal_sample",
            field=models.FileField(default="True", upload_to=""),
        ),
        migrations.AddField(
            model_name="dietmodel",
            name="Gender",
            field=models.CharField(
                choices=[("Female", "Female"), ("Male", "Male")],
                default=1,
                max_length=20,
            ),
        ),
    ]
