# Generated by Django 4.1 on 2023-03-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Tool", "0004_dietmodel_fecal_sample_dietmodel_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietmodel",
            name="Gender",
        ),
    ]
