# Generated by Django 4.1 on 2023-03-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tool", "0005_remove_dietmodel_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietmodel",
            name="Gender",
            field=models.CharField(
                choices=[("Female", "Female"), ("Male", "Male")],
                default=1,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dietmodel",
            name="Fecal_sample",
            field=models.FileField(upload_to=""),
        ),
    ]
