# Generated by Django 4.1 on 2023-03-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tool", "0006_dietmodel_gender_alter_dietmodel_fecal_sample"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietmodel",
            name="Gender",
            field=models.CharField(
                choices=[("Female", "Female"), ("Male", "Male")],
                default="Female",
                max_length=20,
            ),
        ),
    ]
