# Generated by Django 4.1 on 2023-03-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tool", "0007_alter_dietmodel_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dietmodel",
            name="Gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male")], default="F", max_length=2
            ),
        ),
    ]
